import ts from "typescript";
import { literalText, nopPath, pathHandler } from "./handlers";

export const jsDocHandlers = pathHandler({
  [ts.SyntaxKind.JSDocTypeExpression]: nopPath,
  [ts.SyntaxKind.JSDocNameReference]: nopPath,
  [ts.SyntaxKind.JSDocMemberName]: nopPath,
  [ts.SyntaxKind.JSDocAllType]: nopPath,
  [ts.SyntaxKind.JSDocUnknownType]: nopPath,
  [ts.SyntaxKind.JSDocNullableType]: nopPath,
  [ts.SyntaxKind.JSDocNonNullableType]: nopPath,
  [ts.SyntaxKind.JSDocOptionalType]: nopPath,
  [ts.SyntaxKind.JSDocFunctionType]: nopPath,
  [ts.SyntaxKind.JSDocVariadicType]: nopPath,
  [ts.SyntaxKind.JSDocNamepathType]: nopPath,
  [ts.SyntaxKind.JSDocComment]: nopPath,
  [ts.SyntaxKind.JSDocText]: nopPath,
  [ts.SyntaxKind.JSDocTypeLiteral]: nopPath,
  [ts.SyntaxKind.JSDocSignature]: nopPath,
  [ts.SyntaxKind.JSDocLink]: nopPath,
  [ts.SyntaxKind.JSDocLinkCode]: nopPath,
  [ts.SyntaxKind.JSDocLinkPlain]: nopPath,
  [ts.SyntaxKind.JSDocTag]: nopPath,
  [ts.SyntaxKind.JSDocAugmentsTag]: nopPath,
  [ts.SyntaxKind.JSDocImplementsTag]: nopPath,
  [ts.SyntaxKind.JSDocAuthorTag]: nopPath,
  [ts.SyntaxKind.JSDocDeprecatedTag]: nopPath,
  [ts.SyntaxKind.JSDocClassTag]: nopPath,
  [ts.SyntaxKind.JSDocPublicTag]: nopPath,
  [ts.SyntaxKind.JSDocPrivateTag]: nopPath,
  [ts.SyntaxKind.JSDocProtectedTag]: nopPath,
  [ts.SyntaxKind.JSDocReadonlyTag]: nopPath,
  [ts.SyntaxKind.JSDocOverrideTag]: nopPath,
  [ts.SyntaxKind.JSDocCallbackTag]: nopPath,
  [ts.SyntaxKind.JSDocEnumTag]: nopPath,
  [ts.SyntaxKind.JSDocParameterTag]: nopPath,
  [ts.SyntaxKind.JSDocReturnTag]: nopPath,
  [ts.SyntaxKind.JSDocThisTag]: nopPath,
  [ts.SyntaxKind.JSDocTypeTag]: nopPath,
  [ts.SyntaxKind.JSDocTemplateTag]: nopPath,
  [ts.SyntaxKind.JSDocTypedefTag]: nopPath,
  [ts.SyntaxKind.JSDocSeeTag]: nopPath,
  [ts.SyntaxKind.JSDocPropertyTag]: nopPath,
});
